
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-covid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-covid
  template:
    metadata:
      labels:
        app: api-covid
    spec:
      containers:
      - name: api-covid
        image: bhid/api-covid:1.3.2
        env:
        - name: APP_NAME
          value: COVID-19 API
        - name: APP_PORT
          value: "3100"
        - name: LOG_LEVEL
          value: info
        - name: NODE_ENV
          value: production
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: api-covid-service
spec:
  type: NodePort
  selector:
    app: api-covid
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-covid-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.bh.dev
    secretName: bhdev-api-prod-tls
  rules:
  - host: api.bh.dev
    http:
      paths:
      - path: /covid(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: api-covid-service
            port:
              number: 3100
