
apiVersion: v1
kind: Service
metadata:
  name: bhdev-prod-do
spec:
  type: ExternalName
  externalName: nyc3.digitaloceanspaces.com

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bhdev-prod-prsm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /bhdev/prsm/v0.1.0/index.html
    nginx.ingress.kubernetes.io/upstream-vhost: nyc3.digitaloceanspaces.com

spec:
  tls:
  - hosts:
    - bh.dev
    secretName: bhdev-prod-tls-cert
  rules:
  - host: bh.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bhdev-prod-do
            port:
              number: 443

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bhdev-prod-prsm-static
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /bhdev/prsm/v0.1.0/static/$2
    nginx.ingress.kubernetes.io/upstream-vhost: nyc3.digitaloceanspaces.com

spec:
  tls:
  - hosts:
    - bh.dev
    secretName: bhdev-prod-tls-cert
  rules:
  - host: bh.dev
    http:
      paths:
      - path: /static(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bhdev-prod-do
            port:
              number: 443